# Configuration for Alacritty, the GPU enhanced terminal emulator.

import = [
    "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[shell]
program = "/opt/homebrew/bin/fish"
args = ["-l"]

[window]
padding = { x = 8, y = 0}
dynamic_padding = true 
decorations = "buttonless"
opacity = 1.0 

[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular"  }
bold = { style = "Bold" }
italic = { style = "Italic" }
bold_italic = { style = "Bold Italic" }  # Inherits family from normal, Default style: Bold Italic
size = 14.0