# Configuration for Alacritty, the GPU enhanced terminal emulator.

import = [
    "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[shell]
program = "/opt/homebrew/bin/zsh"
args = ["-l"]

[window]
padding = { x = 8, y = 28}  
dynamic_padding = false   
decorations = "transparent" 
opacity = 1.0 

[font]
normal = { family = "JetBrains Mono", style = "Regular"  }
bold = { style = "Bold" }
italic = { style = "Italic" }
bold_italic = { style = "Bold Italic" }  # Inherits family from normal, Default style: Bold Italic
size = 12.0